### ISSUE TITLE
NPE in processUnion

### ISSUE THREAD

**Issue by oobles** [RTBHOUSE/avro-fastserde#15]
We're seeing the following NPE when running on Java 11 using fastserde-1.0.5.  

> com.rtbhouse.utils.avro.FastDeserializerGeneratorException: java.lang.NullPointerException
> 	at com.rtbhouse.utils.avro.FastDeserializerGenerator.generateDeserializer(FastDeserializerGenerator.java:139) ~[avro-fastserde-1.0.5.jar:?]
> 	at com.rtbhouse.utils.avro.FastSerdeCache.buildSpecificDeserializer(FastSerdeCache.java:319) ~[avro-fastserde-1.0.5.jar:?]
> 	at com.rtbhouse.utils.avro.FastSerdeCache.lambda$getFastSpecificDeserializer$1(FastSerdeCache.java:207) ~[avro-fastserde-1.0.5.jar:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
> 	at java.lang.Thread.run(Thread.java:834) [?:?]
> Caused by: java.lang.NullPointerException
> 	at com.rtbhouse.utils.avro.FastDeserializerGenerator.processUnion(FastDeserializerGenerator.java:473) ~[avro-fastserde-1.0.5.jar:?]
> 	at com.rtbhouse.utils.avro.FastDeserializerGenerator.processComplexType(FastDeserializerGenerator.java:157) ~[avro-fastserde-1.0.5.jar:?]
> 	at com.rtbhouse.utils.avro.FastDeserializerGenerator.processRecord(FastDeserializerGenerator.java:264) ~[avro-fastserde-1.0.5.jar:?]
> 	at com.rtbhouse.utils.avro.FastDeserializerGenerator.generateDeserializer(FastDeserializerGenerator.java:102) ~[avro-fastserde-1.0.5.jar:?]
> 	... 6 more

The error is at this line: 

> Symbol.UnionAdjustAction unionAdjustAction = (Symbol.UnionAdjustAction) alternative.symbols[i].production[0];

The production == null.

I think the relevant part of the schema is the "type" in the following:

{
        "name": "name",
        "type": ["null", "string"]
}

**Comment by flowenol** [comment]
Thank you for posting this issue, however it would be helpful if you could provide some more information regarding the version of avro library you are using (especially, if it is above 1.8.2) and the minimal schema which reproduces the issue.
